name: Code Style

on:
  push:
  pull_request:

jobs:
  # Flake 8 for basic code style checks
  flake8:
    name: Flake 8
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install package
      run: |
        pip install .

    - name: Lint with flake8
      run: |
        flake8 document_worker --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 document_worker --count --max-complexity=7 --max-line-length=110 --statistics

  # Typing checks with MyPy
  typing:
    name: Typing
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install package
      run: |
        pip install .

    - name: Typecheck with mypy
      run: |
        mypy --install-types --non-interactive document_worker
